### ISSUE TITLE
what is progress Daredevil kernel?

### ISSUE THREAD

**Issue by Piyushkulkarni21** [GODz-Android-Dev/android_device_micromax_a106#6]
@manjotsidhu  bro when we release daredevil kernel?
its really needed for better rom...pls fix bugs and release it

**Comment by manjotsidhu** [comment]
I won't release it ..  Use that kernel for building roms instead of wakemod

**Comment by manjotsidhu** [comment]
Daredevil is already bugless

**Comment by Piyushkulkarni21** [comment]
nope bro.. wifi jot connecting

**Comment by manjotsidhu** [comment]
Ohh

**Comment by Piyushkulkarni21** [comment]
yeah
pls fix it asap

**Comment by manjotsidhu** [comment]
Ok

**Comment by Piyushkulkarni21** [comment]
comment here when u fix it
