### ISSUE TITLE
Offline charging

### ISSUE THREAD

**Issue by Piyushkulkarni21** [GODz-Android-Dev/android_device_micromax_a106#9]
@manjotsidhu  Pls fix Offline charging issue

**Comment by manjotsidhu** [comment]
In which rom and kernel u are facing this issue ?

**Comment by manjotsidhu** [comment]
So this issue is due to DareDevil Kernel , this issue is being moved to DareDevil repo

**Comment by Sumit199612** [comment]
My IMEI no is not showing how do I write imei no in my Micromax a106.
Pls help

**Comment by Sumit199612** [comment]
My IMEI no is not showing so I m not able to make calls. Pls help

**Comment by manjotsidhu** [comment]
Flash rom on LP v5 firmware then u won't loose IMEI
